name: checkout-action-sample
on: [push]

jobs:
    checkout-action-sample:
        runs-on: ubuntu-latest
        steps:
            - name: list-files-before-checkout
              run: ls -a
            - name: checkout
              uses: actions/checkout@3.5.2
            - name: list-files-after-checkout
              run: ls -a
              