name: container-sample

on: push

jobs:
  container-sample:
    runs-on: ubuntu-latest
    container:
      image: node:latest

    steps:
      - name: log-node-version
        run: node -v