name: hello-world

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print-hello-world
        run: echo "Hello world!"
  powershell-sample:
    runs-on: windows-latest
    steps:
      - name: print-current-directory
        run: Get-Location
    