name: strategy-sample

on:
  - push

jobs:
  strategy-sample:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: log-node-version
        run: node -v