name: strategy-sample

on:
  - push

jobs:
  strategy-sample:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            is_linux: "true"
        exclude:
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      IS_LINUX: ${{ matrix.is_linux }}
    steps:
      - name: log-node-version
        run: |
          node -v
          echo "${IS_LINUX}"
